<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7685f5b2f0c4b68f7671a16baf2fc1a8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7685f5b2f0c4b68f7671a16baf2fc1a8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7685f5b2f0c4b68f7671a16baf2fc1a8::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
